# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool: "Default"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: Use Dotnet 6
    inputs:
      version: '6.0.x'
      includePreviewVersions: true # Required for preview versions

  - task: NuGetToolInstaller@0
    displayName: "Install NuGet"
    inputs:
      versionSpec: 6.0.x
      checkLatest: true

  - task: NuGetCommand@2
    displayName: 'NuGet restore **\*.sln'
    inputs:
      restoreSolution: '**\*.sln'

  - task: alanwales.resharper-code-analysis.custom-build-task.ResharperCli@2
    displayName: "Check for ReSharper code issues"
    inputs:
      solutionOrProjectPath: "ReviewMe.sln"
      additionalArguments: "--no-build"

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      arguments: "--configuration $(buildConfiguration) --logger trx"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: VSTest
      testResultsFiles: "**/*.trx"

  - script: dotnet publish ReviewMe.API/ReviewMe.API.csproj -o $(Build.ArtifactStagingDirectory) --configuration Release /p:EnvironmentName=Development
    displayName: "dotnet publish ReviewMe.API"

  - task: DeleteFiles@1
    displayName: "Delete Jetbrains tools to keep them from being deployed as artifacts"
    inputs:
      SourceFolder: "$(build.artifactstagingdirectory)"
      Contents: "JetBrains*"

  - task: DeleteFiles@1
    displayName: delete custom appsettings configs
    inputs:
      SourceFolder: $(Build.ArtifactStagingDirectory)
      Contents: "appsettings.*.json"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
