global using FluentAssertions;
global using FluentAssertions.Execution;
global using Microsoft.Extensions.Configuration;
global using NSubstitute;
global using NUnit.Framework;
global using ReviewMe.Core.DomainEntities;
global using ReviewMe.Core.Enums;
global using ReviewMe.Core.Infrastructures;
global using ReviewMe.Core.Services;
